version: '3.8'

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio/data:/data
    networks:
      - lakehouse

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - lakehouse

  hive-metastore:
    image: bitnami/hive-metastore:latest
    ports:
      - "9083:9083"
    environment:
      HIVE_METASTORE_DATABASE_HOST: postgres
      HIVE_METASTORE_DATABASE_PORT_NUMBER: 5432
      HIVE_METASTORE_DATABASE_USER: hive
      HIVE_METASTORE_DATABASE_PASSWORD: hive
      HIVE_METASTORE_DATABASE_NAME: metastore
    depends_on:
      - postgres
    networks:
      - lakehouse

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf
    networks:
      - lakehouse

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf
    networks:
      - lakehouse

  trino:
    image: trinodb/trino:latest
    ports:
      - "8088:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      - hive-metastore
    networks:
      - lakehouse

networks:
  lakehouse:
