version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - datalake-network

  spark-jupyter:
    build:
      context: ./images/executor
      dockerfile: Dockerfile
    container_name: spark-jupyter
    environment:
      - MINIO_URI=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    depends_on:
      - minio
    networks:
      - datalake-network

networks:
  datalake-network:
    name: datalake-network
    external: true